server:
  port: 8001
spring:
  application:
    name: BLACKCAT-PLAT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: blackcat-plat-8001.com #起个名字
    prefer-ip-address: true